decks.push(
{
    name: 'Argentina',
    description: 'What does Jeoperdy say about our country',
    fuzzy: false,
    cards: [
         {source: 'THE JESUITS : The first Jesuit Pope was born in this country', target: 'Argentina'},
         {source: 'AROUND THE WORLD WITH MAGELLAN\'S CREW : (Kelly of the Clue Crew points to a map) After reaching South American waters, Magellan spent the winter of 1520 in Puerto San JuliÃ¡n, today in this southern region.', target: 'Patagonia'},
         {source: 'THE PAMPAS : The Pampas are vast plains of this country, from the Gran Chaco in its north to Patagonia in the south', target: 'Argentina'},
         {source: 'BRAZILIAN GEOGRAPHY : Brazil\'s tourism industry depends in part on these spectacular falls on the border with Argentina', target: 'Iguazu Falls'},
         {source: '2 COMPLETELY UNRELATED ITEMS : Country bordered by Chile & the Atlantic Ocean & businesswoman behind her self-named \"No. 5\" perfume', target: 'Argentina & Chanel'},
         {source: 'INTELLIGENCE : In 1960 agents of this Israeli spy service abducted Nazi Adolf Eichmann in Argentina', target: 'the Mossad'},
         {source: 'BUT THE END IS ROUGH : In October 1967 the revolutionary dreams of this man from Argentina ended via bullets in Bolivia', target: 'Che Guevara'},
         {source: 'WE\'VE GOT YOU SURROUNDED! : Brazil, Argentina, Bolivia', target: 'Paraguay'},
         {source: 'INTERNATIONAL TV TITLES : In Argentina this 1960s show became \"Viaje a las Estrellas\"', target: 'Star Trek'},
         {source: 'INTERNATIONAL GEOGRAPHIC : Though called a \"rio\", or river, this body that divides Uruguay & Argentina is considered an estuary', target: 'the RÃ­o de la Plata'},
         {source: 'MINORITY POPULATIONS : A large Welsh community has been thriving in Chubut Province in this country\'s Patagonia region for over 100 years', target: 'Argentina'},
         {source: 'GEORGIAS ON MY MIND : Possession of South Georgia Island in the South Atlantic is disputed by these 2 nations', target: 'Argentina & the U.K.'},
         {source: 'GOIN\' COUNTRY : 10 times as long as it is wide, this South American country gained independence in 1818', target: 'Chile'},
         {source: 'FACE, THE NATION : Cristina Kirchner of this country ably succeeded her husband', target: 'Argentina'},
         {source: 'ARGENTINA : This city\'s Avenida 9 de Julio is one of the widest city streets in the world', target: 'Buenos Aires'},
         {source: 'ARGENTINA : In 1985 Argentina settled a more than 100-year-old dispute with this neighbor over islands in the Beagle Channel', target: 'Chile'},
         {source: 'ARGENTINA : Jose Hernandez wrote the epic poem \"Martin Fierro\", a tale about the life of these cowboys', target: 'gauchos'},
         {source: 'ARGENTINA : In 1974 not Evita but this widow of Juan Peron became the first female president in the western hemisphere', target: 'Isabel'},
         {source: 'ARGENTINA : Greek for \"between the rivers\", this region lying between the Parana & Uruguay rivers is known for its waterfalls', target: 'Mesopotamia'},
         {source: 'SOUTH AMERICA : Argentina, where the wind comes sweepin\' down this fertile plain with about 3/5 of the country\'s people', target: 'the Pampas'},
         {source: 'SOUTH AMERICA : 2 miles wide, these falls form part of Argentina\'s northern border', target: 'Iguazu Falls'},
         {source: 'CROSS WORLD CLUES \"P\" : Scrub plateau in southern Argentina (9)', target: 'Patagonia'},
         {source: 'IT\'S OPENING NIGHT ON BROADWAY! : On Sept. 25, 1979 Patti LuPone sang \"Don\'t Cry For Me Argentina\" in this Hal Prince-directed musical at the Broadway Theatre', target: 'Evita'},
         {source: 'PLAY SETTINGS : The musical \"Evita\": set in this country', target: 'Argentina'},
         {source: 'LANGUAGES OF SOUTH AMERICA : With 1.5 million speakers, Italian is this country\'s second-most spoken language; Arabic is third & German is fourth', target: 'Argentina'},
         {source: 'GOVERNORS SPEAK : This S.C. Gov. said, \"I developed a relationship with what started out as a dear, dear friend from Argentina\"', target: '(Mark) Sanford'},
         {source: 'CELEBRITY COUNTRY OF ORIGIN : Actor Antonio Banderas', target: 'Spain'},
         {source: 'AROUND THE WHIRLED : Country with Pampas & circumstance: REGAIN TAN', target: 'Argentina'},
         {source: 'IT\'S ANDREW! : Andrew Lloyd Webber composed \"Don\'t Cry For Me, Argentina\" for this Broadway show', target: 'Evita'},
         {source: 'INSIDE THE COUNTRY : You\'ve got \"men\" in Armenia & a \"gent\" in this nation', target: 'Argentina'},
         {source: 'PRO TEENS : Lionel Messi from this country joined Spanish pro soccer at 13 when a team agreed to pay for his growth hormones', target: 'Argentina'},
         {source: 'LATINOS IN HOLLYWOOD : Last name of Fernando, a star in Argentina before moving to the U.S.; his son Lorenzo & grandson A.J. act, too', target: 'Lamas'},
         {source: 'LEFTY : Born in Argentina, he aided Castro in Cuba\'s revolution before being killed in Bolivia', target: 'Che Guevara'},
         {source: '50 YEARS AGO--1961 : This Nazi captured in Argentina was sentenced to death in Jerusalem on December 15', target: 'Eichmann'},
         {source: 'I\'M ABSOLUTELY SURE : In area, it\'s the second-largest country in South America', target: 'Argentina'},
         {source: 'STADIUMS BY COUNTRY : Estadio Presidente Peron', target: 'Argentina'},
         {source: 'SOUTH AMERICAN GEOGRAPHY : (Kelley of the Clue Crew stands before a map) In 1860 the United Provinces of La Plata changed its name to Argentina; 21 years later, it expanded its territory by adding this region whose name comes from the Spanish for \"big foot\"', target: 'Patagonia'},
         {source: '\"GO\" BABY, GO! : If you go to Argentina, you must do this national dance', target: 'tango'},
         {source: 'ARTISTS : After visits to this country in the 1850s, Frederic Church painted its Cotopaxi volcano', target: 'Ecuador'},
         {source: 'BORN & DIED : Born: June 14, 1928, Rosario, Argentina. Died: Oct. 9, 1967, Bolivia', target: 'Che Guevara'},
         {source: '\"POT\"s & \"PAN\"s : This olympics-like sports event for western hemisphere countries was first held in Argentina in 1951', target: 'the Panamerican Games'},
         {source: 'BODIES OF WATER : The name of this South American estuary means \"silver river\"', target: 'RÃ­o de la Plata'},
         {source: 'PIRATE HAIKU--\"AR\" : Patagonia / Aye lads, this country make way / Loot Buenos Aires', target: 'Argentina'},
         {source: 'THE GENTLE ART OF RUGBY : The USA\'s national team is the Eagles; Argentina\'s is Los these, aka mountain lions', target: 'Pumas'},
         {source: 'ISLANDS OF THE ATLANTIC : (Tom Ritchie of Lindblad Expeditions stands in front of a war monument in the Falkland Islands) Stanley is the only city on the Falkland Islands, and underwent bombing during the 1982 conflict between Britain and this country', target: 'Argentina'},
         {source: 'WINE FROM WHERE? : You know about Argentinian wines, but try the rose from this country, Argentina\'s littlest neighbor', target: 'Uruguay'},
         {source: 'TAKE ME TO YOUR WORLD LEADER : Don\'t cry for me, President Cristina Fernandez De Kirchner', target: 'Argentina'},
         {source: 'CASUAL & SPORTY FASHION : This clothing company is named for a region in Southern Argentina & Chile', target: 'Patagonia'},
         {source: 'THEY WERE DROPOUTS : This dropout & actress was married to the president of Argentina from 1946 to 1952', target: 'Eva Peron'},
         {source: '20th CENTURY HISTORY : Support from laborers called descamisados, \"shirtless ones\", brought him to power in Argentina in 1946', target: 'Juan Peron'},
         {source: 'YOU ARE THE JUAN : This town\'s swallows return each spring following a 12,000-mile round trip to Argentina', target: 'San Juan Capistrano'},
         {source: 'IT\'S IN ARGENTINA : The tomb of Jose de San Martin, who liberated Argentina from Spain, is in a cathedral in this capital', target: 'Buenos Aires'},
         {source: 'IT\'S IN ARGENTINA : Cerro Mercedario & Cerro Nacimiento are Argentine peaks in this chain', target: 'the Andes'},
         {source: 'IT\'S IN ARGENTINA : Monica Lewinsky was one at the White House', target: 'an intern'},
         {source: 'IT\'S IN ARGENTINA : Fossil tracks of Limayichnus major, a type of this, can be seen near El Chocon, Argentina', target: 'a dinosaur'},
         {source: 'IT\'S IN ARGENTINA : A subspecies of this type of large cat lives on the island of Sumatra', target: 'a tiger'},
         {source: 'IT\'S IN ARGENTINA : Discovered in 1520, this large island Argentina shares with Chile has a name that means \"land of fire\"', target: 'Tierra del Fuego'},
         {source: 'IT\'S IN ARGENTINA : At its widest point more than 120 miles across, this Argentine \"rio\" isn\'t a river at all, but an estuary', target: 'the Rio de la Plata'},
         {source: 'IT\'S IN ARGENTINA : Any very large person, like pitcher Ed Halicki', target: 'a giant'},
         {source: 'IT\'S IN ARGENTINA : A large structure for open-air sports or other entertainments', target: 'an arena'},
         {source: 'IT\'S IN ARGENTINA : Light-sensitive membrane on the back of your eye', target: 'retina'},
         {source: 'WELL, EXHUME ME! : Her body was stolen & sent to Italy after her husband was deposed; it was returned to Argentina in 1974', target: 'Eva PerÃ³n'},
         {source: 'MOUNTAIN COUNTRY : The summit of Aconcagua', target: 'Argentina'},
         {source: 'WORLD OF GESTURES : (Jimmy of the Clue Crew twirls a finger near his temple.) In much of the world, the twirled finger means \"you\'re crazy\", but in Argentina, it means you may have one of these--pick up!', target: 'a phone call'},
         {source: 'OFFICIAL LANGUAGES : Argentina', target: 'Spanish'},
         {source: 'HE DIED A DEADLY DEATH : After his death at age 78 on July 1, 1974, Argentina could cry for this 3-time president too', target: 'Juan PerÃ³n'},
         {source: 'FUN WITH WORDS : Its the New World country that takes its name from a Latin word for a metal', target: 'Argentina'},
         {source: 'WEIRD CRITTERS : Found in Argentina, the pink fairy species of this armored animal reaches only a length of about 5 inches', target: 'an armadillo'},
         {source: 'YOU\'VE GOT YOUR BORDERS : To the east, Argentina; to the west, the Pacific', target: 'Chile'},
         {source: 'THE COUNTRY AS DESCRIBED BY THE ONION : \"Nearly 15 feet wide\", this nation\'s been \"preventing Argentina from enjoying the Pacific Ocean since 1818\"', target: 'Chile'},
         {source: 'TOWERS : The Renoir Towers rise over the Rio de la Plata in this South American country', target: 'Argentina'},
         {source: 'SOUTH OF THE EQUATOR : This country\'s Christchurch is the world\'s southernmost city with more than 250,000 people', target: 'New Zealand'},
         {source: 'SOUTH OF THE EQUATOR : The Gran Chaco, an arid subtropical region, covers parts of Uruguay & Bolivia & the northern part of this country', target: 'Argentina'},
         {source: 'IDEAS FOR TOURISM CAMPAIGNS : Our Andes are dandy! Only Brazil has more people in South America, but they don\'t have our coffee. Hail...', target: 'Colombia'},
         {source: 'ANAGRAMS : A South American country: RAIN AGENT', target: 'Argentina'},
         {source: 'MILITARY DUDES : Manuel Belgrano was a prominent military leader in this S. American country\'s fight for independence from Spain', target: 'Argentina'},
         {source: 'FAMOUS TRIALS : (Jack Ford delivers the clue.) \"I had orders\" was among his statements at his trial in Israel after being seized in Argentina in 1960; he got the only death sentence Israel has ever imposed', target: '(Adolf) Eichmann'},
         {source: 'HISTORIC FIGURES SPEAK : I made a women\'s branch of my hubby\'s political party in 1949 but died 3 years later; still, don\'t cry for me, Argentina', target: 'Evita PerÃ³n'},
         {source: 'JUST DESERTS : The Patagonian Desert lies west of Buenos Aires in this country', target: 'Argentina'},
         {source: 'THE BRITISH PRIME MINISTER WHEN : ...Argentina invaded the Falkland Islands', target: 'Margaret Thatcher'},
         {source: 'HEAD SOUTH FROM : ...this country & you might find yourself in Paraguay, Argentina or Chile', target: 'Bolivia'},
         {source: 'THE WORLD AT WAR : Unprepared for this man leading an army force over the Andes in 1817, the Spanish Empire lost Chile & Argentina', target: 'JosÃ© de San MartÃ­n'},
         {source: 'MISSING WORDS : Los desaparecidos--those missing at the hands of Argentina\'s former dictatorship--translates to this', target: 'the disappeared'},
         {source: 'FILL IN THE SONG TITLE : Madonna as Evita: \"D.C.F.M.A.\"', target: '\"Don\'t Cry For Me Argentina\"'},
         {source: 'MOUNTAINS : Of South America\'s 10 highest peaks, 9 of them rise all or in part in this country', target: 'Argentina'},
         {source: '\"A\" TRAVEL CATEGORY : Lots of chaps wear chaps in the Gaucho Parade in Salta in this country', target: 'Argentina'},
         {source: 'CITIES : For a short time in the 1950s, La Plata, Argentina was named for her', target: 'Eva Peron'},
         {source: 'THE NORTHERNMOST NATION : Argentina, Ecuador, Bolivia', target: 'Ecuador'},
         {source: 'FLAGS : The stripes on Argentina\'s flag are in \"celeste y blanca\", this shade of blue & white', target: 'sky blue'},
         {source: '\"A\" IN GEOGRAPHY : Argentina\'s lowest point is Valdes Peninsula; its highest is this mountain', target: 'Aconcagua'},
         {source: 'COUNTRIES BY NEWSPAPERS : Diario de los Andes, The Buenos Aires Herald', target: 'Argentina'},
         {source: 'IT\'S A BIT CHILE TODAY : Chile shares its longest land border with this country', target: 'Argentina'},
         {source: 'REDS : Born in Argentina, this commie helped take over Cuba & later died in Bolivia', target: 'Che Guevara'},
         {source: 'DINOSAURS : The name of the Laplatasaurus honors a river on the border of Uruguay & this country', target: 'Argentina'},
         {source: 'BRITISH ROYALS IN THE MILITARY : In 1982 Prince Andrew flew helicopters during a war against this country', target: 'Argentina'},
         {source: 'WORLD HISTORY : At the urging of this general now on the 5-peso note, Argentina declared its independence from Spain July 9, 1816', target: '(Jose de) San Martin'},
         {source: 'TANGO : The tango is the national dance of this South American country & its 40 million citizens', target: 'Argentina'},
         {source: 'DUTCH ROYALTY : Don\'t cry for Princess Maxima, wife of the heir to the Dutch throne; she was born in this South American country', target: 'Argentina'},
         {source: 'WOMEN IN HISTORY : In the late 1940s she founded a female branch of her husband\'s political party in Argentina', target: 'Eva Peron'},
         {source: 'TOUGH BODIES OF WATER : The Uruguay River forms the border between Uruguay & Argentina & most of the border between Argentina & this country', target: 'Brazil'},
         {source: 'THE FEMININE MISTAKE : In 1951 she thought folks wouldn\'t have a problem with her running for VP of Argentina; she was wrong', target: 'Evita Peron'},
         {source: 'GREEN ACRES : The heart of Argentina\'s agricultural region is these grassy plains covering 300,000 square miles', target: 'the pampas'},
         {source: 'AROUND THE WORLD : In the board game Risk, they\'re 2 of the 4 South American countries represented', target: '(2 of) Brazil, Argentina, Peru, & Venezuela'},
         {source: 'MUSEUMS : The highlight of Argentina\'s national history museum in this city is Candido Lopez\'s historical canvases', target: 'Buenos Aires'},
         {source: 'INTERNATIONAL : Cities in this large South American country include Mendoza, Rosario & Mar del Plata', target: 'Argentina'},
         {source: 'I\'M INTO WORLD \"P\"s : It\'s bounded by Bolivia, Brazil & Argentina', target: 'Paraguay'},
         {source: 'GEOGRAPHY : Hundreds of waterfalls make up the spectacular Iguacu Falls on the border of these 2 countries', target: 'Brazil & Argentina'},
         {source: 'THE SMALLEST IN AREA : Argentina, Armenia, Angola', target: 'Armenia'},
         {source: 'PLACES IN SONG : This show tune says, \"All through my wild days, my mad existence, I kept my promise, don\'t keep your distance\"', target: '\"Don\'t Cry For Me Argentina\"'},
         {source: 'WHO SAYS : 90% of Argentina\'s supply of this comes from people donating to members of their own families', target: 'blood'},
         {source: 'SHE USED TO BE IN CHARGE : President Isabel Peron', target: 'Argentina'},
         {source: 'SOUTH AMERICA : Bernardo O\'Higgins is called \"The Liberator\" of this long nation & also founded its navy', target: 'Chile'},
         {source: 'YOU\'VE GOT TO FIGHT : In 1982 Prince Andrew flew helicopters for England in an undeclared war with this country', target: 'Argentina'},
         {source: 'NAME THAT COUNTRY : This country takes its name from a term for a precious metal', target: 'Argentina'},
         {source: 'A WORLD OF FACTS : Nestor Kirchner is the current president of this South American country', target: 'Argentina'},
         {source: 'AROUND THE HORN : The southernmost point in South America, Cape Horn is part of this country', target: 'Chile'},
         {source: '\"DON\'T\" YOU KNOW THIS SONG? : Buenos Aires held back a sniffle when this Madonna hit went to No. 8 in 1997', target: '\"Don\'t Cry For Me Argentina\"'},
         {source: 'ALPHABETICALLY FIRST : Of the countries of mainland South America', target: 'Argentina'},
         {source: 'GEOGRAPHY : The ownership of the islands of Tierra del Fuego is shared by these 2 nations', target: 'Chile & Argentina'},
         {source: 'BODIES OF WATER : The name of this waterfall on the Brazil-Argentina border is derived from a Guarani word meaning \"great water\"', target: 'IguassÃº'},
         {source: 'SOUTH AMERICAN HISTORY : During WWII this colonel amassed power in Argentina; in 1946 he was elected president', target: 'Juan Peron'},
         {source: 'MONEY FROM HOME : If your grandma in Argentina wanted to send you money, she\'d convert these into dollars', target: 'pesos'},
         {source: 'NAME THAT AUTOCRAT : Argentina 1946-1955', target: '(Juan) PerÃ³n'},
         {source: 'THE 19th CENTURY : In 1825 patriots crossed the Rio de la Plata from Argentina to fight for this country\'s freedom from Brazil', target: 'Uruguay'},
         {source: 'LET\'S DANCE! : Britannica calls the Milonga, a dance from this South American country, \"fast, sensual, and disreputable\"', target: 'Argentina'},
         {source: 'BLOWIN\' IN THE WIND : A pampero is a sudden cold summer wind in this second-largest South American country', target: 'Argentina'},
         {source: 'TAKE ME TO THE RIVER : When visiting Argentina, visit the Cataratas, or falls of, this river, which include the Tres Mosqueteros', target: 'Iguazu'},
         {source: 'NAME THAT NATION : Despite its larger resources, Brazil lost an 1820s war with Argentina that resulted in this new country between them', target: 'Uruguay'},
         {source: 'COUNTRIES BY NEWSPAPERS : El Cronista & El Patagonico', target: 'Argentina'},
         {source: 'SHOW BUSINESS GROUPS : (Honorary Clue Crew member Dayna Devon from Extra reports from an awards show.) The Golden Globe Awards are given by the HFPA, a group whose reporters hail from places like Argentina, Egypt & Taiwan', target: 'the Hollywood Foreign Press Association'},
         {source: 'CALM DOWN, YOU\'RE HISTORICAL! : Don\'t cry for her; in 1951, she was nominated for vice president of Argentina', target: 'Evita (Peron)'},
         {source: 'CALM DOWN, YOU\'RE HISTORICAL! : In 1982 this \"Iron Lady\" prime minister ordered an attack to stop Argentina from claiming the Falkland Islands', target: 'Margaret Thatcher'},
         {source: 'JOSE CAN YOU SEE : The largest of the 4 modern countries Jose de San Martin helped liberate from European rule', target: 'Argentina'},
         {source: 'PEACE, LOVE & UNDERSTANDING : A mountain pass is home to the \"Christ of the Andes\" statue symbolizing peace between these 2 countries', target: 'Chile & Argentina'},
         {source: 'ANDREW LLOYD WEBBER : This musical was the happy result of a 1974 visit to Argentina by Lloyd Webber\'s collaborator Tim Rice', target: 'Evita'},
         {source: '\"DON\'T\" FORGET THIS SONG : Julie Covington made a popular recording of this song from \"Evita\"', target: '\"Don\'t Cry For Me Argentina\"'},
         {source: 'FOREIGN ANIMAL NOISES : In Argentina they berp; Swedish ones kvack while hopping', target: 'frogs'},
         {source: 'THE MOST POPULOUS NATION : Spain, Mexico, Argentina', target: 'Mexico'},
         {source: 'GEOGRAPHY : One of the 2 South American countries trying to claim Graham Land, part of the British Antarctic territory', target: 'Argentina (or Chile)'},
         {source: 'THEIR NATIVE SOIL : Soccer great Diego Maradona', target: 'Argentina'},
         {source: 'ANNUAL EVENTS : On August 17, this country honors the death of native son & freedom fighter Jose de San Martin', target: 'Argentina'},
         {source: 'CURRENT EVENTS : The Falkland Current flows for hundreds of miles up the east coast of this country', target: 'Argentina'},
         {source: 'THE SMALLEST IN AREA : Panama, Brazil, Argentina', target: 'Panama'},
         {source: 'PLACES TO PAY IN PESOS : Use pesos to pay for the CD of \"Evita\" in La Plata in this country', target: 'Argentina'},
         {source: 'WHAT \"A\" COUNTRY : It occupies most of southern South America', target: 'Argentina'},
         {source: 'HOT SPOTS : When it hit 120 on Dec. 11, 1905 in Rivadavia in this country the gauchos must have stayed in the sombra', target: 'Argentina'},
         {source: 'GAMES : The Cup of the Americas is up for grabs in matches between the U.S. & Argentina in this mounted game', target: 'polo'},
         {source: 'IT BORDERS BOTH : Venezuela & Argentina', target: 'Brazil'},
         {source: '\"E\"PICS : It had an interesting casting choice, Madonna as the first lady of Argentina', target: 'Evita'},
         {source: 'NEXT TO BRAZIL : It\'s the largest country in area with which Brazil has a border', target: 'Argentina'},
         {source: 'BORDERS : Argentina\'s border with this country is 3,200 miles long, about the same as its coastline', target: 'Chile'},
         {source: 'WOMEN OF COUNTRY : Isabel Peron', target: 'Argentina'},
         {source: 'THE TWENTIETH : A nation shares its name with this traditional 20th wedding anniversary present', target: 'China'},
         {source: 'PLACES : Stanley is the capital of these islands that were a bone of contention between the U.K. & Argentina', target: 'Falkland Islands (or Malvinas)'},
         {source: 'THE MOST POPULOUS NATION : Mexico, Brazil, Argentina', target: 'Brazil'},
         {source: 'INDEPENDENCE DAY : On September 7 you can party on down to Rio & celebrate this South American country\'s independence', target: 'Brazil'},
         {source: 'HOLIDAY HISTORY : In 1970 this country moved carnival from before Lent to late July', target: 'Cuba'},
         {source: 'THE LARGEST IN AREA : Argentina, Chile, Peru', target: 'Argentina'},
         {source: 'THE RIVER : The Paraguay River originates in the highlands of Mato Grosso in this country', target: 'Brazil'},
         {source: 'RUN FOR THE BORDER : From Santiago, Chile', target: 'Argentina'},
         {source: 'SALUTE THE FLAGS : This second-largest South American country\'s flag is seen here', target: 'Argentina'},
         {source: 'RANCHES : At about 12,000 sq. mi., Strangeray Springs, a cattle ranch (or station) in this country, is bigger than Vermont', target: 'Australia'},
         {source: 'THE THREE : The three countries closest to Antarctica', target: 'Argentina, Chile & New Zealand'},
         {source: 'ARGENTINA : Famed Argentine composer Alberto Ginastera drew from the dances & songs of these cowboys in his early works', target: 'gauchos'},
         {source: 'ARGENTINA : More than 2/3 of Argentina\'s population lives in this fertile plain that has some of the world\'s best topsoil', target: 'Pampas'},
         {source: 'ARGENTINA : Ushuaia, the world\'s southernmost city, lies on this island territory of Argentina', target: 'Tierra del Fuego'},
         {source: 'ARGENTINA : Argentina has 2 major political parties: the radical Civic Union & the Justicialist Party, also called this', target: 'Peronist Party (party of Juan Peron)'},
         {source: 'ARGENTINA : Both Argentina & the Rio de la Plata derive their names from the Latin word for this', target: 'silver'},
         {source: 'WORLD GOVERNMENT : Although they made the musical about Evita, this third wife of Juan Peron was president of Argentina', target: 'Isabel Peron'},
         {source: 'WORLD LEADERS : After its president Fernando de la Rua resigned December 20, 2001, Adolfo Rodriguez Saa got the post & lasted a week', target: 'Argentina'},
         {source: 'WORLD FLAGS : This South American nation\'s flag is based on one raised by Gen. Manuel Belgrano in 1812', target: 'Argentina'},
         {source: 'SOUTH AMERICAN CAPITALS : About one-third of Argentina\'s population lives within the metropolitan area of this capital city', target: 'Buenos Aires'},
         {source: 'THE NORTHERNMOST NATION : Bolivia, Ecuador, Argentina', target: 'Ecuador'},
         {source: 'OLD POETIC FORMS : The Cielito, \"darling\", is associated with this cowboy literature of Argentina & Uruguay', target: 'gaucho'},
         {source: 'EGGS-ACTLY : The Sauropod, a dinosaur the size of a bus, came from eggs discovered in this country\'s Patagonia region', target: 'Argentina'},
         {source: 'PROVINCES : Chaco & La Pampa', target: 'Argentina'},
         {source: '1946: This 50-year-old ex-colonel was elected president of Argentina on March 28, 1946', target: 'Juan Peron'},
         {source: 'ANAGRAMMED WORLD CAPITALS : In South America: AS I TANGO', target: 'Santiago'},
         {source: '\"P\"LACES : More than half the population of this country perished in an 1864-1870 war with Argentina, Brazil & Uruguay', target: 'Paraguay'},
         {source: 'ANAGRAMMED COUNTRIES : In South America: Ant in gear', target: 'Argentina'},
         {source: 'NAME THE COUNTRY : \"Don\'t Cry For Me,\" this country', target: 'Argentina'},
         {source: 'WATERFALLS : This scenic waterfall on the Brazil-Argentina border actually consists of about 275 individual cataracts', target: 'Iguazu Falls'},
         {source: 'MOVIE SONGS : 1996: \"Don\'t Cry For Me, Argentina\"', target: 'Evita'},
         {source: 'IT BORDERS BOTH : Ecuador & Chile', target: 'Peru'},
         {source: 'THE WESTERN HEMISPHERE : Portuguese for \"beautiful\", it\'s a city in northern Argentina, & also an old name for Taiwan', target: 'Formosa'},
         {source: 'AUTHORS\' NATIVE LANDS : Writer of \"Ficciones\" Jorge Luis Borges', target: 'Argentina'},
         {source: 'INTERNATIONAL BOOKS & AUTHORS : Argentina\'s Manuel Puig gave us the \"Kiss of\" this \"Woman\"; I read about it on the \"web\"', target: '\"Kiss of the Spider Woman\"'},
         {source: 'NOTABLE NAMES : A hero to many, he trained as a doctor in Argentina before becoming a revolutionary & dying in Bolivia', target: 'Che Guevara'},
         {source: '\"F\" IN GEOGRAPHY : In the 1980s Argentina & Great Britain fought a war over these South American islands', target: 'the Falklands (or Malvinas)'},
         {source: '\"A\" IN GEOGRAPHY : This country controls the eastern half of Tierra del Fuego, largest island in an archipelago of the same name', target: 'Argentina'},
         {source: 'THE \"A\"-TEAM : Both this country & the Rio de la Plata, its major river estuary, were named for silver', target: 'Argentina'},
         {source: 'ROAM : Go due west from Sao Paulo & you\'ll next make your guay into this country', target: 'Paraguay'},
         {source: 'SOUTH OF THE EQUATOR : The Gran Chaco is a low, flat plain covering western Paraguay, southern Bolivia & the northern part of this country', target: 'Argentina'},
         {source: 'WORLD LIT : \"Heartbreak Tango\" was the second novel by Manuel Puig, one of this country\'s most famous authors', target: 'Argentina'},
         {source: 'WOMEN IN HISTORY : Argentina cried for her when this former actress & first lady died of cancer in 1952', target: 'Eva Peron'},
         {source: 'THEY WROTE THE SONGS : \"I Don\'t Know How To Love Him\" & \"Don\'t Cry For Me, Argentina\"', target: 'Andrew Lloyd Webber & Tim Rice'},
         {source: 'COUNTRY NAME ORIGINS : For the abundance of the metal found there, this South American country\'s name is from the Latin for \"silver\"', target: 'Argentina'},
         {source: 'THE SMALLEST IN AREA : Argentina, Brazil, Peru', target: 'Peru'},
         {source: 'FOREIGN NATIONAL PARKS : Gran Paradiso', target: 'Italy'},
         {source: 'ISLANDS OF THE ATLANTIC : In 1998 oil drilling operations began in the waters off these islands claimed by Argentina & Great Britain', target: 'Falkland/Malvinas Islands'},
         {source: 'NATIONS\' MOST POPULOUS CITIES : Argentina', target: 'Buenos Aires'},
         {source: 'A COMMUNIST PLOT : Buried in Santa Clara, Cuba this revolutionary leader was born in Argentina in 1928', target: 'Ernesto \"Che\" Guevara'},
         {source: 'AROUND THE WORLD : Argentina, Bolivia & Brazil could say to this small country, \"Halt, we\'ve got you surrounded!\"', target: 'Paraguay'},
         {source: 'AROUND THE WORLD : In 1976 soccer\'s Diego Maradona joined this country\'s national team when he was only 16 years old', target: 'Argentina'},
         {source: 'DON\'T CRY FOR ME, ARGENTINA : 2 of the 5 countries that border Argentina', target: 'Bolivia, Brazil, Chile, Paraguay &/or Uruguay'},
         {source: 'DON\'T CRY FOR ME, ARGENTINA : Argentina claimed these islands in 1820; the British took them over in 1833 without firing a shot', target: 'Falklands (or Malvinas)'},
         {source: 'DON\'T CRY FOR ME, ARGENTINA : Spanish sailors named this city in honor of St. Mary, patron saint of good winds', target: 'Buenos Aires'},
         {source: 'DON\'T CRY FOR ME, ARGENTINA : This army colonel was Argentina\'s president from 1946 to 1955 & again from 1973 to 1974', target: 'Juan Peron'},
         {source: 'CHORUS LINES : Its chorus says, \"All through my wild days, my mad existence, I kept my promise, don\'t keep your distance\"', target: '\"Don\'t Cry For Me Argentina\"'},
         {source: 'WORLD CAPITALS : The name of this capital of Argentina means \"fair winds\" or \"good air\"', target: 'Buenos Aires'},
         {source: 'COUNTRIES BY REGION : Chaco Central, Pampa de las Salinas, Chaco Austral', target: 'Argentina'},
         {source: 'INTERNATIONAL FOOD & DRINK : Ninos Envueltos, or \"wrapped children\", are taste treats in this second-largest South American country', target: 'Argentina'},
         {source: 'PENINSULAS : The peninsula at the northwestern edge of this continent has been claimed by England, Chile & Argentina', target: 'Antarctica'},
         {source: 'ALL THE TEA : This South American country produced 55,000 tons in 1997; tea there is \"like silver\"', target: 'Argentina'},
         {source: 'WHAT \"A\" COUNTRY! : It\'s the only \"A\" country whose currency is the peso', target: 'Argentina'},
         {source: 'THE 1950s : The U.S. & Argentina were among the 12 countries who signed a treaty to preserve this continent', target: 'Antarctica'},
         {source: 'OFFICIAL LANGUAGES : Argentina', target: 'Spanish'},
         {source: 'NAME THE MUSICAL : Magaldi, Peron\'s mistress, People of Argentina', target: 'Evita'},
         {source: 'SPECIAL FORCES : \"By way of deception, thou shalt do war\" is the motto of this agency that captured Eichmann in Argentina', target: 'The Mossad (from Israel)'},
         {source: 'WORLD GEOGRAPHY : The name of this waterfall on the Brazil-Argentina border comes from a Guarani word for \"great water\"', target: 'Iguazu Falls'},
         {source: '50 YEARS AGO : Argentina\'s new 1949 constitution meant this incumbent president could succeed himself', target: 'Juan Peron'},
         {source: 'COUNTRIES BY REGION : Cordoba, La Pampa, Tierra del Fuego', target: 'Argentina'},
         {source: 'YESTERDAY : He first led his red-shirted Italian legion in the 1840s, fighting for Uruguay against Argentina', target: 'Giuseppe Garibaldi'},
         {source: 'HOLIDAYS : This country observes June 10 as Malvinas Day', target: 'Argentina'},
         {source: 'AROUND THE LITERARY WORLD : It was the native country of Benito Lynch, a master of the gaucho novel', target: 'Argentina'},
         {source: 'WORLD CUP \'98 : Argentina didn\'t \"kick\" about this controversial tie-breaking method after using it to beat England', target: 'Penalty kicks/shootout'},
         {source: 'WORLD HODGEPODGE : Pato, a combination of basketball & this game played on horseback, is quite popular in Argentina', target: 'Polo'},
         {source: 'WATER, WATER EVERYWHERE : These falls on the Brazil-Argentina border are almost 4 times the width of Niagara Falls', target: 'Iguazu Falls'},
         {source: 'GEOGRAPHICAL EXTREMES : Only 4 nations lie south of 40 degrees south latitude: Australia, New Zealand, Argentina & this one', target: 'Chile'},
         {source: 'SECOND PLACE : South America\'s second largest country in area, it borders the largest', target: 'Argentina'},
         {source: 'HORSE BREEDS : The Criollo is a breed from this country & is popular with the gauchos of the Pampas', target: 'Argentina'},
         {source: 'GEOGRAPHY : Bigfoot walks the Pacific Northwest; this area, whose name means big foot, is in Argentina', target: 'Patagonia'},
         {source: '1945: In a surprise coup, he overthrew Argentina\'s new government & set up his own cabinet', target: 'Juan Peron'},
         {source: 'WORLD GEOGRAPHY : The Casa Rosada, residence of this country\'s president, stands on the Plaza de Mayo in Buenos Aires', target: 'Argentina'},
         {source: '1974: The Western Hemisphere\'s first female head of state was this country\'s Isabel Peron', target: 'Argentina'},
         {source: 'POWER PLAYS : In this Andrew Lloyd Webber musical, an actress becomes the most powerful woman in Argentina', target: 'Evita'},
         {source: 'SOUTH OF THE EQUATOR : In 1842 the British made Stanley the capital of these later war-torn islands off Argentina', target: 'Falkland Islands (or Malvinas)'},
         {source: '\"C\" THE WORLD : Henry Kissinger described this long, narrow country as a blade \"pointed at the heart of Antarctica\"', target: 'Chile'},
         {source: 'TOUGH GEOGRAPHY : Provinces of this country include El Oro, Chimborazo & Colon or the Galapagos Islands', target: 'Ecuador'},
         {source: 'TOUGH GEOGRAPHY : One of Puerto Rico\'s major rivers shares its name with this estuary that separates Uruguay & Argentina', target: 'Rio de la Plata'},
         {source: 'FAMOUS NAMES : In 1951 she was nominated for vice president of Argentina, but was forced to withdraw from the race', target: 'Eva Peron'},
         {source: 'WORLD TRAVEL : Known for its snow festival, Bariloche, Argentina is one of the top ski resorts in these mountains', target: 'Andes'},
         {source: 'WORLD HISTORY : In 1828 Brazil & Argentina recognized this neighboring country as an independent republic', target: 'Uruguay'},
         {source: 'RECURRENCES : Each year a flock of these birds travels between Goya, Argentina & a mission in California', target: 'swallows'},
         {source: 'ATHLETES : This man who led Argentina to the 1986 World Cup soccer title played for Italy\'s Napoli from 1984 to 1991', target: 'Diego Maradona'},
         {source: 'WORLD GEOGRAPHY : This island group also claimed by Argentina was named by the British for a treasurer of the British navy', target: 'Falkland (or Malvinas) Islands'},
         {source: 'COUNTRIES OF THE WORLD : Its borders with Bolivia & Peru are much shorter than its border with Argentina', target: 'Chile'},
         {source: 'WHEAT : South America\'s main wheat-growing area is the Pampa in this country', target: 'Argentina'},
         {source: 'THE 1970s : In 1978 these 2 South American countries almost went to war over 3 islands in the Beagle Channel', target: 'Argentina & Chile'},
         {source: 'GEOGRAPHY : The Patagonian region of South America lies mainly in this country', target: 'Argentina'},
         {source: 'AROUND THE WORLD : The Cueca is a flirtatious courtship dance from this narrow country that borders Argentina', target: 'Chile'},
         {source: 'MODERN HISTORY : Traced to Argentina in 1960, this Nazi official was transported to Israel, tried, and executed', target: 'Adolf Eichmann'},
         {source: 'WORLD LEADERS : After 18 years in exile, he returned to Argentina in 1973', target: 'Juan PerÃ³n'},
         {source: 'NATIONAL PARKS OF THE WORLD : Argentina & Brazil have national parks to preserve the wildlife & beauty of these extensive waterfalls', target: 'Iguazu Falls'},
         {source: 'SOUTH AMERICA : 80% of Argentina\'s farm products come from this feritle plain', target: 'Pampas'},
         {source: 'FLIGHTLESS BIRDS : In central Argentina, gauchos with bolas hunt this large bird for sport', target: 'Rhea'},
         {source: 'ISLANDS : What Argentina calls the Islas Malvinas, England calls this', target: 'Falkland Islands'},
         {source: 'THE 1980s : This country occupied the Falkland Islands for about 10 weeks in 1982', target: 'Argentina'},
         {source: 'PARKS : This country\'s Cape Horn national park is the most southerly park in the Western Hemisphere', target: 'Chile'},
         {source: 'CIVIL WARS : Gaucho troops supported the Federalists against the Unitarians in this country\'s 19th c. strife', target: 'Argentina'},
         {source: '\"A\" IN GEOGRAPHY : There\'s a Liberty cap on the coat of arms of this South American country', target: 'Argentina'},
         {source: 'GEOGRAPHY : 131 feet below sea level, Argentina\'s lowest point is on this dry, windy region\'s Valdez Peninsula', target: 'Patagonia'},
         {source: 'LANGUAGES : There are still a few thousand speakers of Welsh in areas of Patagonia in this country', target: 'Argentina'},
         {source: 'MOUNTAINS : Mount Aconcagua, the Western Hemisphere\'s highest peak, lies on the border of Chile & this country', target: 'Argentina'},
         {source: 'ISLANDS : Argentina\'s claim to this British south Atlantic colony dates back to 1820', target: 'Falkland Islands/Islas Malvinas'},
         {source: '1952: The city of La Plata, Argentina was renamed for her after her July 26 death', target: 'Eva Peron'},
         {source: 'WORLD GEOGRAPHY : Argentina declared its independence from this country in 1816', target: 'Spain'},
         {source: 'DESPOTS & DICTATORS : In the early 1800s Juan Manuel de Rosas went from gaucho to head honcho of this country', target: 'Argentina'},
         {source: 'HORSES : The smallest breed of horse, the Falabella, was developed by ranchers in this S. American country', target: 'Argentina'},
         {source: 'BOOKS & AUTHORS : Manuel Puig\'s novel about the kiss of this woman was banned in his native Argentina', target: '\"The Kiss of the Spider Woman\"'},
         {source: 'ARGENTINA : Sailors named this place for the patron saint Mary of Good Air', target: 'Buenos Aires'},
         {source: 'ARGENTINA : Argentina\'s 1990 loss to Cameroon was called one of the biggest upsets ever in this tournament', target: 'the World Cup'},
         {source: 'ARGENTINA : Both the country & the Rio de la Plata were named for this metal', target: 'silver'},
         {source: 'ARGENTINA : President Menem represents the Justicialist Party, more commonly called this', target: 'Peronist Party'},
         {source: 'ARGENTINA : In 1984 Argentina settled its dispute over the Beagle Channel with this neighbor', target: 'Chile'},
         {source: 'INTERNATIONAL PARKS : 1 of 2 South American countries each having a park on its side of Iguacu Falls', target: 'Brazil (or Argentina)'},
         {source: 'WORLD GEOGRAPHY : 1 of the 2 Central American countries with only 1 sea coast', target: 'Belize & El Salvador'},
         {source: 'SONG LYRICS : Evita sang, \"Don\'t\" do this \"for me Argentina -- the truth is I never left you\"', target: 'Cry'},
         {source: 'ARGENTINA : Argentina has won 2 of the last 3 World Cup titles in this sport, the country\'s most popular', target: 'Futbol/Soccer'},
         {source: 'ARGENTINA : Candidates for president & vice president must be citizens by birth & of this religion', target: 'Roman Catholic'},
         {source: 'ARGENTINA : In 1983 Raul Alfonsin was elected president, handing this party its 1st defeat', target: 'The Peronistas (the party of Juan Peron)'},
         {source: 'ARGENTINA : These cowboys were the rank & file of the army that won independence from Spain', target: 'Gauchos'},
         {source: 'ARGENTINA : This almost treeless region of Argentina is the agricultural & industrial heart of the nation', target: 'Pampas'},
         {source: 'ARGENTINA : Like Washington, D.C., this city is a federal district', target: 'Buenos Aires'},
         {source: 'ARGENTINA : The Argentine version of this dance developed from the milonga & the habanera in the 1800s', target: 'Tango'},
         {source: 'ARGENTINA : Largest bird of the Pampas, it can be tamed & kept as a farmyard pet', target: 'Rhea'},
         {source: 'ARGENTINA : Jesuits were the 1st to cultivate this species of holly that\'s made into a tea-like drink', target: 'Mate'},
         {source: 'ARGENTINA : He has been called the \"George Washington of Argentina\"', target: 'Jose de San Martin'},
         {source: 'ANIMALS : In Argentina, rheas are rounded up in order to get these', target: 'tailfeathers'},
         {source: 'GEOGRAPHIC PAIRS : Island off New Jersey or Argentina, but Argentines call it \"Isla de los Estados\"', target: 'Staten Island'},
         {source: 'GEOGRAPHY : According to the Britannica, geographic distinction of the city of Ushuaia, Argentina', target: 'southernmost city in the world'},
         {source: 'SOUTH AMERICA : Besides those of Spanish origin, they\'re Argentina\'s largest ethnic group', target: 'Italians'},
         {source: 'BIRDS : Around Oct. 22, the swallows leave Capistrano to winter in this country, so don\'t cry for them', target: 'Argentina'},
         {source: 'POTPOURRI : It\'s the 1st letter of alphabet that\'s not the 1st letter of a South American country', target: 'D'},
         {source: 'SOUTH AMERICA : This \"cattle country\" is also world\'s 4th largest producer of wool', target: 'Argentina'},
         {source: 'WARS : In 19th C., Brazil, Argentina & Uruguay wiped out over 80% of this nearby country\'s population', target: 'Paraguay'},
         {source: 'FINAL JEOPARDY!: FAMOUS EUROPEANS: After moving to Argentina in 1949, this industrialist was named a righteous gentile by Yad Vashem', target: 'Oskar Schindler'},
         {source: 'FINAL JEOPARDY!: COUNTRYS\' HIGHEST POINTS: This country is home to the highest mountain outside Asia', target: 'Argentina'},
         {source: 'FINAL JEOPARDY!: WORLD CURRENCY: With inflation raging there at more than 2.2 million%, this nation issued $100 billion notes in 2008', target: 'Zimbabwe'},
         {source: 'FINAL JEOPARDY!: FOREIGN COUNTRIES: Of the world\'s 10 largest countries in total area, the 2 whose names start & end with \"A\" (Algeria is number 11)', target: 'Australia & Argentina'},
         {source: 'FINAL JEOPARDY!: AMERICAN ENTERTAINERS: \"Evita\"\'s \"Don\'t Cry for Me Argentina\" was inspired by a 1969 concert of hers in London; she left the stage after 15 minutes', target: 'Judy Garland'},
         {source: 'FINAL JEOPARDY!: SOUTH AMERICA: Alphabetically, they\'re the first & last of the 7 countries where the Andes are found', target: 'Argentina & Venezuela'},
         {source: 'FINAL JEOPARDY!: NOTORIOUS: Using the aliases James Ryan & Harry Place, they boarded a steamer for Argentina in February 1901', target: 'Butch Cassidy & The Sundance Kid'},
         {source: 'FINAL JEOPARDY!: FAMOUS NICKNAMES: This famous 20th century nickname is the Argentinian equivalent of \"Y\'know?\" or \"Hey, you!\"', target: 'Che (for Che Guevara, who was born in Argentina)'},
         {source: 'FINAL JEOPARDY!: WORLD GEOGRAPHY: This country contains South America\'s highest & lowest points', target: 'Argentina'},
         {source: 'FINAL JEOPARDY!: GEOGRAPHY: It\'s the southernmost independent country in the world', target: 'Chile (which goes down around Tierra Del Fuego & sweeps a little south of Argentina)'},
         {source: 'FINAL JEOPARDY!: SOUTH AMERICA: These are the only 2 independent countries in South America named for a famous person', target: 'Colombia & Bolivia'}
    ]
});